# Generated by Django 5.2 on 2025-05-30 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='admin_code',
            field=models.TextField(blank=True, null=True, verbose_name='Código de admin.py'),
        ),
        migrations.AddField(
            model_name='project',
            name='models_code',
            field=models.TextField(blank=True, null=True, verbose_name='Código de models.py'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
