# Generated by Django 5.2 on 2025-06-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_usuario_validated_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
